ALTER TABLE topics ADD COLUMN IF NOT EXISTS skill_rating DOUBLE PRECISION DEFAULT 1000;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS memory_strength DOUBLE PRECISION DEFAULT 1.0;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS attempts_solved INTEGER DEFAULT 0;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS attempts_total INTEGER DEFAULT 0;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMP;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS mastery_probability DOUBLE PRECISION DEFAULT 0.0;
