ALTER TABLE topics ADD COLUMN IF NOT EXISTS easiness_factor DOUBLE PRECISION DEFAULT 2.5;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS repetition_interval INTEGER DEFAULT 0;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS last_quality INTEGER;
